### ISSUE TITLE
Vấn đề với makefile

### ISSUE THREAD

**Issue by vusonbmt** [esp8266vn/esp8266.vn#11]
Em có vấn đề chỗ make với esp-iot-basic 1 chút. Em thay đổi makefile 1 số chỗ

```
XTENSA      ?= 
SDK_BASE    ?= /home/hocarm/esp-open-sdk/sdk
ESPTOOL     ?= /home/hocarm/esp-open-sdk/esptool/esptool.py
```

Bước 1 em chạy terminal trong thư mục esp-iot-basic
Kết quả 

```
hocarm@sc:~/esp-iot-basic$ make
/home/hocarm/esp-open-sdk/esptool/esptool.py elf2image  main.out -o main
esptool.py v1.2-dev
Error calling xtensa-lx106-elf-readelf, do you have Xtensa toolchain in PATH?
Makefile:19: recipe for target 'main.bin' failed
make: *** [main.bin] Error 1
```

Bước 2 em chạy lại path bằng lệnh
`export PATH=/home/hocarm/esp-open-sdk/xtensa-lx106-elf/bin:$PATH` sau đó `make` lại
Kết quả 

```
hocarm@sc:~/esp-iot-basic$ export PATH=/home/hocarm/esp-open-sdk/xtensa-lx106-elf/bin:$PATH
hocarm@sc:~/esp-iot-basic$ make
/home/hocarm/esp-open-sdk/esptool/esptool.py elf2image  main.out -o main
esptool.py v1.2-dev
```

Coi như ok.
Giờ em muốn bỏ bước 2 đi mà chỉ chạy mỗi `make` nó tự set PATH rồi make luôn thì làm thế nào anh ? Em có thử thay 
`XTENSA     ?= /home/hocarm/esp-open-sdk/xtensa-lx106-elf/bin/` nhưng không được
Báo lỗi

```
/home/hocarm/esp-open-sdk/esptool/esptool.py elf2image  main.out -o main
esptool.py v1.2-dev
Error calling xtensa-lx106-elf-readelf, do you have Xtensa toolchain in PATH?
Makefile:19: recipe for target 'main.bin' failed
make: *** [main.bin] Error 1

```

**Comment by tuanpmt** [comment]
Lỗi này do esptool.py nó gọi xtensa-lx106-elf-readelf để bóc tách firmware, nên bắt buộc phải export Xtensa toolchain vào PATH thôi. Để mình note lại trong kia
