### ISSUE TITLE
Tốc độ baud nạp chương trình ?

### ISSUE THREAD

**Issue by vusonbmt** [esp8266vn/esp8266.vn#15]
Em hỏi cái tốc độ baud 480600 như của anh làm sao chỉnh được lên tới tốc độ đó được anh nhỉ ? Của em mặc định toàn 9600 nên flash chậm quá.
Còn sau khi flash có tự đổi baud không anh ? Sao em để 9600 nhận dữ liệu bị lỗi ký tự.
Và sau khi flash là firmware mới hoàn toàn? Có liên quan gì tới firmware của NodeMCU nữa không anh?

**Comment by tuanpmt** [comment]
Lên tới `921600` luôn ấy chứ.
Xem chỗ này: https://github.com/esp8266vn/esp-iot-basic/blob/master/Makefile#L39

Sau khi flash xong chạy thì sdk đưa về 115200
sau khi flash, là firmware mới 100% của mình

**Comment by vusonbmt** [comment]
Em coi code anh rồi, em có thử lại phải chỉnh code main.c  
`uart_div_modify(0, UART_CLK_FREQ / 480600);`
thì mới nạp theo makefile a được, còn baud là nó lấy theo cái firmware mình nạp gần nhất là baud bao nhiêu.
Cái hiển thị em vẫn đang bị lỗi để e check lại.
Em xài ESPv12+PL2303 chứ k có NodeMCU nên tự làm khó mình nhiều hơn :)),về thực tế thì 2 cái này cũng k khác gì nhau cả

**Comment by vusonbmt** [comment]
E đã fix được lỗi, vấn đề ở chỗ chưa reset lại sau khi nạp và không kết nối chân GPIO với GND nữa là hiển thị đúng

```
Trước
�l�l�|�là|�lì�|ì�bb��nlnn�ìbplr�rlpònà�l�bnâ|�ìb�ònnî�l�l`��nln�nb�`pònà�râà�bnâ�ìb�nnî�l`�nnl`�nrn�ìlpònà�r�àììb�â|ììb�ònnî��`nn�l`nr�nò�lrn�òl�âìnì�ròn|ì�lll`â�ll�l`âr�lìl�l`âr���l`rlr�âb�bbbr�lpbì�nînnâ�lòpl�ll��`nü��bllr�â�blbr�rlrònâ�ìbr�bìâbì�ìlpìì�l�ìbìòn�P�
Sau
hello world
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 3
cnt 

connected with SATO, channel 1
dhcp client start...
ip:192.168.1.103,mask:255.255.255.0,gw:192.168.1.1
```

Có cái sau scandone và `connected with SATO, channel 1` hình như vẫn còn gì đó của firmware cũ chứ ko mất hết đâu anh

---

Sau khi xóa trắng thì nạp lại sẽ mất hết các lỗi ở trên
