### ISSUE TITLE
CI merge and build failed on 5/11/2016

### ISSUE THREAD

**Issue by hieucdtspk** [esp8266vn/esp8266.vn#37]
Ủa sao nãy h pull request mà CI nó merge rùi build failed hoài vậy ta? đã fetch, merge, mkdocs serve thử OK rùi mới commit cẩn thận rùi mà ta!? @tuanpmt @

**Comment by hieucdtspk** [comment]
Build log of CI mấy dòng cuối nek @tuanpmt 

> INFO    -  Copying '/home/travis/build/esp8266vn/esp8266.vn/site' to 'gh-pages' branch and pushing to GitHub. 
> ERROR   -  Failed to deploy to GitHub with error: 
> remote: Anonymous access to esp8266vn/esp8266.vn.git denied.
> fatal: Authentication failed for 'https://@github.com/esp8266vn/esp8266.vn.git/'

The command "mkdocs gh-deploy -v --clean --remote-name gh-token" exited with 1.
Done. Your build exited with 1.

**Comment by tuanpmt** [comment]
Cái này không phải do anh, không hiểu sao hôm nay build token lại bị mất, mấy bữa đâu có sao đâu ta. Để e check lại

**Comment by hocarm** [comment]
a @hieucdtspk build mkdocs dưới local luôn ạ, e toàn edit file md cho lẹ ko à 🍡 , chẳng bao giờ có lỗi 😄

**Comment by tuanpmt** [comment]
Mới có lỗi CI kìa 😄

**Comment by hocarm** [comment]
vãi,  thế không phải lỗi tại em rồi a @tuanpmt  😄

**Comment by hocarm** [comment]
CI của em check nó vẫn dính lỗi như của a @hieucdtspk  nè a @tuanpmt 

```
INFO    -  Copying '/home/travis/build/esp8266vn/esp8266.vn/site' to 'gh-pages' branch and pushing to GitHub. 
ERROR   -  Failed to deploy to GitHub with error: 
remote: Anonymous access to esp8266vn/esp8266.vn.git denied.
fatal: Authentication failed for 'https://@github.com/esp8266vn/esp8266.vn.git/'
```

**Comment by danghuutoan** [comment]
same here :((

**Comment by tuanpmt** [comment]
Không hiểu bên Travis nó đổi gì mà gh-token của pull-req toàn bị null, để a check
